# Generated by Django 5.1.7 on 2025-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_input', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comfort', models.TextField()),
            ],
        ),
    ]
