# Generated by Django 5.1.7 on 2025-03-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='user',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
