# Generated by Django 5.1.7 on 2025-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_emotion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='emotion_analysis',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='comfort',
            field=models.TextField(default='unknown'),
        ),
    ]
